server:
  port: 8083
spring:
  application:
    name: consumer-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
# 消费者将要去访问的微服务名称
service-url:
    nacos-user-service: http://nacos-provider