server:
  port: 9003
spring:
  application:
    name: server-provider9003
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
